CREATE TABLE IF NOT EXISTS NATIONS (
  NAT_ID CHAR(8) PRIMARY KEY,
  NAT_Name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ORIGINS (
  ORI_ID INT AUTO_INCREMENT PRIMARY KEY,
  NAT_ID CHAR(8) NOT NULL,
  ORI_Name VARCHAR(255) NOT NULL,
  CONSTRAINT fk_origins_nations FOREIGN KEY (NAT_ID) REFERENCES NATIONS(NAT_ID)
);

CREATE TABLE IF NOT EXISTS GENRES (
  GEN_ID CHAR(8) PRIMARY KEY,
  GEN_Name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLISHERS (
  PUB_ID VARCHAR(10) PRIMARY KEY,
  PUB_Name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS (
  USER_ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_Name VARCHAR(255) NOT NULL,
  USER_Birthday DATE NULL,
  USER_Email VARCHAR(255) NULL,
  USER_Address VARCHAR(255) NULL,
  USER_Phone CHAR(10) NULL
);

CREATE TABLE IF NOT EXISTS USER_ROLE (
  USER_ID INT PRIMARY KEY,
  UR_ROLE BOOLEAN NOT NULL DEFAULT 0,
  CONSTRAINT fk_user_role_users FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE IF NOT EXISTS BOOKS (
  BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
  GEN_ID CHAR(8) NOT NULL,
  ORI_ID INT NOT NULL,
  PUB_ID VARCHAR(10) NOT NULL,
  BOOK_Name VARCHAR(255) NOT NULL,
  BOOK_Amount INT NOT NULL DEFAULT 0,
  BOOK_PRICE INT NOT NULL,
  BOOK_PurchaseDate DATE NULL,
  BOOK_Image VARCHAR(255) NULL,
  CONSTRAINT fk_books_genres FOREIGN KEY (GEN_ID) REFERENCES GENRES(GEN_ID),
  CONSTRAINT fk_books_origins FOREIGN KEY (ORI_ID) REFERENCES ORIGINS(ORI_ID),
  CONSTRAINT fk_books_publishers FOREIGN KEY (PUB_ID) REFERENCES PUBLISHERS(PUB_ID)
);

CREATE TABLE IF NOT EXISTS ORDERS (
  OR_ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID INT NOT NULL,
  OR_Status VARCHAR(255) NOT NULL,
  OR_DATE DATE NOT NULL,
  CONSTRAINT fk_orders_users FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE IF NOT EXISTS DETAIL_ORDERS (
  BOOK_ID INT NOT NULL,
  OR_ID INT NOT NULL,
  OD_Amount INT NOT NULL,
  OD_Cost FLOAT NOT NULL,
  PRIMARY KEY (BOOK_ID, OR_ID),
  CONSTRAINT fk_detail_orders_books FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
  CONSTRAINT fk_detail_orders_orders FOREIGN KEY (OR_ID) REFERENCES ORDERS(OR_ID)
);
