INSERT INTO NATIONS (NAT_ID, NAT_Name)
SELECT 'VN', 'Việt Nam' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM NATIONS WHERE NAT_ID = 'VN');

INSERT INTO NATIONS (NAT_ID, NAT_Name)
SELECT 'US', 'Hoa Kỳ' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM NATIONS WHERE NAT_ID = 'US');

INSERT INTO NATIONS (NAT_ID, NAT_Name)
SELECT 'JP', 'Nhật Bản' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM NATIONS WHERE NAT_ID = 'JP');

INSERT INTO ORIGINS (ORI_ID, NAT_ID, ORI_Name)
SELECT 1, 'VN', 'Hà Nội' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ORIGINS WHERE ORI_ID = 1);

INSERT INTO ORIGINS (ORI_ID, NAT_ID, ORI_Name)
SELECT 2, 'US', 'New York' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ORIGINS WHERE ORI_ID = 2);

INSERT INTO ORIGINS (ORI_ID, NAT_ID, ORI_Name)
SELECT 3, 'JP', 'Tokyo' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ORIGINS WHERE ORI_ID = 3);

INSERT INTO GENRES (GEN_ID, GEN_Name)
SELECT 'SGK', 'Sách giáo khoa' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE GEN_ID = 'SGK');

INSERT INTO GENRES (GEN_ID, GEN_Name)
SELECT 'TT', 'Tiểu thuyết' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE GEN_ID = 'TT');

INSERT INTO GENRES (GEN_ID, GEN_Name)
SELECT 'TRT', 'Truyện tranh' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE GEN_ID = 'TRT');

INSERT INTO PUBLISHERS (PUB_ID, PUB_Name)
SELECT 'NXBTRE', 'NXB Trẻ' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PUBLISHERS WHERE PUB_ID = 'NXBTRE');

INSERT INTO PUBLISHERS (PUB_ID, PUB_Name)
SELECT 'NXBGD', 'NXB Giáo Dục' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PUBLISHERS WHERE PUB_ID = 'NXBGD');

INSERT INTO PUBLISHERS (PUB_ID, PUB_Name)
SELECT 'NXBKD', 'NXB Kim Đồng' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PUBLISHERS WHERE PUB_ID = 'NXBKD');

INSERT INTO USERS (USER_ID, USER_Name, USER_Password, USER_Birthday, USER_Email, USER_Address, USER_Phone)
SELECT 1, 'admin', 'admin123', '2000-01-01', 'admin@bookland.local', 'HCM City', '0900000001' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USERS WHERE USER_ID = 1);

INSERT INTO USERS (USER_ID, USER_Name, USER_Password, USER_Birthday, USER_Email, USER_Address, USER_Phone)
SELECT 2, 'customer01', '123456', '2001-02-02', 'customer01@bookland.local', 'Ha Noi', '0900000002' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USERS WHERE USER_ID = 2);

INSERT INTO USER_ROLE (USER_ID, UR_ROLE)
SELECT 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USER_ROLE WHERE USER_ID = 1);

INSERT INTO USER_ROLE (USER_ID, UR_ROLE)
SELECT 2, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USER_ROLE WHERE USER_ID = 2);

INSERT INTO BOOKS (BOOK_ID, GEN_ID, ORI_ID, PUB_ID, BOOK_Name, BOOK_Amount, BOOK_PRICE, BOOK_PurchaseDate, BOOK_Image)
SELECT 1, 'TT', 1, 'NXBTRE', 'Dế Mèn Phiêu Lưu Ký', 50, 65000, CURRENT_DATE, 'assets/img/logo/logo2.png' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM BOOKS WHERE BOOK_ID = 1);

INSERT INTO BOOKS (BOOK_ID, GEN_ID, ORI_ID, PUB_ID, BOOK_Name, BOOK_Amount, BOOK_PRICE, BOOK_PurchaseDate, BOOK_Image)
SELECT 2, 'TRT', 3, 'NXBKD', 'Conan Tập 1', 120, 25000, CURRENT_DATE, 'assets/img/logo/logo2.png' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM BOOKS WHERE BOOK_ID = 2);

INSERT INTO BOOKS (BOOK_ID, GEN_ID, ORI_ID, PUB_ID, BOOK_Name, BOOK_Amount, BOOK_PRICE, BOOK_PurchaseDate, BOOK_Image)
SELECT 3, 'SGK', 1, 'NXBGD', 'Sách Giáo Khoa Toán 1', 200, 18000, CURRENT_DATE, 'assets/img/logo/logo2.png' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM BOOKS WHERE BOOK_ID = 3);
